version: '3.8'

networks:
  pongy:
    ipam:
      driver: default
      config:
          - subnet: "13.37.0.0/16"

services:
  db:
      container_name: postgres
      image: postgres:13
      ports:
        - 5434:5432 #host:container
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=123
        - POSTGRES_DB=pong_db
      networks:
        - pongy
      restart: always

  frontend:
      build: ./frontend
      container_name: frontend
      image: frontend
      env_file:
        - ./frontend/code/.env.local
      networks:
        - pongy
      depends_on:
        - backend
      ports:
        - 80:3001 #host:container
      restart: always

  backend:
      build: ./backend
      container_name: backend
      image: backend
      env_file:
        - ./backend/code/.env
      networks:
        - pongy
      depends_on:
        - db
      ports:
        - 8080:3000 #host:container
      restart: always