FROM node:latest

COPY ./code /home/code

COPY script.sh /home/script.sh
WORKDIR /home/code/src

EXPOSE 3000
# RUN cd /home/code/src
RUN npm install @prisma/client
RUN npm i -g @nestjs/cli
RUN npm i



CMD [ "/home/script.sh" ]