FROM node:latest

COPY ./code /home/code
COPY script.sh /home/script.sh

WORKDIR /home/code/src

EXPOSE 3000

RUN chmod +x /home/script.sh

RUN npm i -g @nestjs/cli
RUN npm i
RUN npx prisma generate

CMD [ "/home/script.sh" ]
# ENTRYPOINT [ "npm", "run", "start" ]